services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=city_bike
    volumes:
      - ${PWD}/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - city_bike_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ${PWD}/pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    networks:
      - city_bike_network
  
  webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile  
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:root@pgdatabase:5432/city_bike
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
    ports:
      - "8081:8080"
    entrypoint: /entrypoint.sh
    command: webserver
    depends_on:
    - pgdatabase
    networks:
    - city_bike_network

  scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile  
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:root@pgdatabase:5432/city_bike
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
    entrypoint: /entrypoint.sh
    command: scheduler
    depends_on:
      - pgdatabase
    networks:
      - city_bike_network

networks:
  city_bike_network:
    name: city_bike_network
    